buildah: set --use-signing-config=false for cosign
Cosign v3 does not accept our signing method by default. Cosign thinks
that we're using a "signing config", which is supposed to include the
URLs of services like Rekor etc., and refuses to operate since we're
also providing URLs explicitly as CLI arguments:

    Error: cannot specify service URLs and use signing config

However, at the same time, the TUF mirror deployed in Konflux doesn't
actually provide the signing config that Cosign wants:

    WARNING: Could not fetch signing_config.json from the TUF mirror
    (encountered error: getting info for target "signing_config.v0.2.json":
     target signing_config.v0.2.json not found).

The reason why Cosign thinks we're using a signing config is because the
use-signing-config flag defaults to true and overrides the non-existence
of the actual signing config.

Explicitly disable the use of signing config to fix the problem.

Signed-off-by: Adam Cmiel <acmiel@redhat.com>